export type Fighter = {
  id: number;
  name: string;
  nickname: string;
  record: string;
  stance: "Orthodox" | "Southpaw" | "Switch";
  note: string;
  initials: string;
  accent: string;
  waitMin: number;
  waitMax: number;
  windowMs: number;
  perfectMs: number;
  sharpMs: number;
  cleanMs: number;
  feintChance: number;
};

export const FIGHTERS: Fighter[] = [
  {
    id: 1,
    name: "Rico Vale",
    nickname: "Warmup",
    record: "4-3",
    stance: "Orthodox",
    note: "Telegraphs the whole night. Use him to find your timing.",
    initials: "RV",
    accent: "#f59e0b",
    waitMin: 900,
    waitMax: 2200,
    windowMs: 540,
    perfectMs: 210,
    sharpMs: 300,
    cleanMs: 400,
    feintChance: 0,
  },
  {
    id: 2,
    name: "June Pell",
    nickname: "Soft Hands",
    record: "6-4",
    stance: "Orthodox",
    note: "Quiet feet. The hand still arrives on schedule.",
    initials: "JP",
    accent: "#fb923c",
    waitMin: 850,
    waitMax: 2300,
    windowMs: 510,
    perfectMs: 205,
    sharpMs: 290,
    cleanMs: 390,
    feintChance: 0,
  },
  {
    id: 3,
    name: "Mason Ruiz",
    nickname: "Practice Pad",
    record: "8-5",
    stance: "Southpaw",
    note: "Long pauses. Don't drift. The cue is still coming.",
    initials: "MR",
    accent: "#fbbf24",
    waitMin: 800,
    waitMax: 2500,
    windowMs: 490,
    perfectMs: 200,
    sharpMs: 280,
    cleanMs: 380,
    feintChance: 0,
  },
  {
    id: 4,
    name: "Delia Shore",
    nickname: "The Clinic",
    record: "11-2",
    stance: "Orthodox",
    note: "Measures you. Slap when the light hits, not when you guess.",
    initials: "DS",
    accent: "#f43f5e",
    waitMin: 750,
    waitMax: 2400,
    windowMs: 470,
    perfectMs: 195,
    sharpMs: 270,
    cleanMs: 365,
    feintChance: 0,
  },
  {
    id: 5,
    name: "Hank Briggs",
    nickname: "Open Palm",
    record: "9-6",
    stance: "Orthodox",
    note: "Heavy, honest, and a little slow. Don't get greedy.",
    initials: "HB",
    accent: "#ea580c",
    waitMin: 700,
    waitMax: 2200,
    windowMs: 450,
    perfectMs: 190,
    sharpMs: 260,
    cleanMs: 350,
    feintChance: 0,
  },
  {
    id: 6,
    name: "Nia Cole",
    nickname: "Switch Stance",
    record: "12-3",
    stance: "Switch",
    note: "She changes shape mid-wait. The cue does not.",
    initials: "NC",
    accent: "#e11d48",
    waitMin: 700,
    waitMax: 2600,
    windowMs: 430,
    perfectMs: 185,
    sharpMs: 255,
    cleanMs: 340,
    feintChance: 0.08,
  },
  {
    id: 7,
    name: "Omar Voss",
    nickname: "The Clock",
    record: "14-1",
    stance: "Orthodox",
    note: "Counts in his head. Break the rhythm or he owns you.",
    initials: "OV",
    accent: "#d97706",
    waitMin: 650,
    waitMax: 2000,
    windowMs: 410,
    perfectMs: 180,
    sharpMs: 250,
    cleanMs: 330,
    feintChance: 0.1,
  },
  {
    id: 8,
    name: "Tess Quinn",
    nickname: "Hair Trigger",
    record: "13-4",
    stance: "Southpaw",
    note: "Short waits. If you blink, you're already late.",
    initials: "TQ",
    accent: "#fb7185",
    waitMin: 500,
    waitMax: 1600,
    windowMs: 395,
    perfectMs: 175,
    sharpMs: 240,
    cleanMs: 315,
    feintChance: 0.12,
  },
  {
    id: 9,
    name: "Bo Harlan",
    nickname: "Iron Cheek",
    record: "16-2",
    stance: "Orthodox",
    note: "Takes a clean slap and keeps staring. Stay composed.",
    initials: "BH",
    accent: "#b45309",
    waitMin: 800,
    waitMax: 2700,
    windowMs: 380,
    perfectMs: 170,
    sharpMs: 235,
    cleanMs: 300,
    feintChance: 0.14,
  },
  {
    id: 10,
    name: "Kira Bell",
    nickname: "The Pause",
    record: "15-3",
    stance: "Southpaw",
    note: "Lets the silence get loud, then moves. Don't bite early.",
    initials: "KB",
    accent: "#be123c",
    waitMin: 1100,
    waitMax: 3000,
    windowMs: 365,
    perfectMs: 165,
    sharpMs: 228,
    cleanMs: 290,
    feintChance: 0.22,
  },
  {
    id: 11,
    name: "Rex Calder",
    nickname: "Feint",
    record: "18-1",
    stance: "Switch",
    note: "The twitch is a lie. Wait for the real light.",
    initials: "RC",
    accent: "#c2410c",
    waitMin: 700,
    waitMax: 2400,
    windowMs: 350,
    perfectMs: 160,
    sharpMs: 220,
    cleanMs: 280,
    feintChance: 0.42,
  },
  {
    id: 12,
    name: "Marisol Vega",
    nickname: "Ghost Hand",
    record: "17-2",
    stance: "Southpaw",
    note: "Almost no windup. If you see it, you already waited too long.",
    initials: "MV",
    accent: "#e11d48",
    waitMin: 550,
    waitMax: 1900,
    windowMs: 335,
    perfectMs: 155,
    sharpMs: 210,
    cleanMs: 268,
    feintChance: 0.28,
  },
  {
    id: 13,
    name: "Jed Crowe",
    nickname: "The Silence",
    record: "19-0",
    stance: "Orthodox",
    note: "Doesn't blink. The wait can stretch until your nerve goes.",
    initials: "JC",
    accent: "#92400e",
    waitMin: 900,
    waitMax: 3200,
    windowMs: 320,
    perfectMs: 150,
    sharpMs: 200,
    cleanMs: 255,
    feintChance: 0.34,
  },
  {
    id: 14,
    name: "Asha Kane",
    nickname: "Zero Frame",
    record: "21-1",
    stance: "Switch",
    note: "The window is a sliver. Perfect or nothing.",
    initials: "AK",
    accent: "#9f1239",
    waitMin: 480,
    waitMax: 1700,
    windowMs: 300,
    perfectMs: 145,
    sharpMs: 190,
    cleanMs: 240,
    feintChance: 0.3,
  },
  {
    id: 15,
    name: "Cassian Ward",
    nickname: "Last Light",
    record: "24-0",
    stance: "Orthodox",
    note: "The card ends here. He waits until you flinch, then he doesn't.",
    initials: "CW",
    accent: "#f59e0b",
    waitMin: 600,
    waitMax: 2800,
    windowMs: 280,
    perfectMs: 140,
    sharpMs: 180,
    cleanMs: 225,
    feintChance: 0.48,
  },
];

export const TOTAL_ROUNDS = FIGHTERS.length;
export const MAX_STRIKES = 3;
